# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: lgalke/swiss

# title: "Mach. Learn. Commun. Lab."
title: "NAIS Lab"
tagline: "Interpretability-informed control for AI safety" # Used by seo tag
description: >
  The Nordic AI Safety Lab at the University of Southern Denmark develops methods to understand and control AI systems.
  We believe that interpretability—understanding the internal mechanisms of AI—is essential for achieving meaningful control
  and ensuring safety. Our research focuses on agentic & multi-agent safety,
  control & containment, interpretability & transparency, and safety evaluation.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naislab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: "" # the GitHub repo name for your project
github_username: naislab

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: naislab

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
markdown: kramdown

# Exclude files from processing
exclude:
  - CLAUDE.md

# Metadata for jekyll seo tag
author:
  name: "Lukas Galke Poech"
  url: "https://lgalke.github.io"
  twitter: "LukasGalke"

# Plugins
plugins:
  - jekyll-seo-tag


# Collections

collections:
  team:
    order:
      - lukas-galke.md